Added: -Restart service command line option
Changed:
- Updated single character command line options for consistency
- Documentation to reflect all changes in the latest release

Fixed:
- Failure to remove PID file on service stop

diff --git a/noirnet b/noirnet
--- a/noirnet
+++ b/noirnet
@@ -6,8 +6,8 @@
 
 # App version and name
 APP_NAME="NoirNet"
-VERSION=1.2.2
-LAST_UPDATED="2024-11-27"
+VERSION=1.3.0
+LAST_UPDATED="2024-11-29"
 
 # TODO:
 #  - Add more notification methods (email, slack, discord, etc.)
@@ -565,11 +565,24 @@ stop_service() {
     if kill -0 "$pid" >/dev/null 2>&1; then
         log_message "INFO" "Stopping $APP_NAME service with PID $pid..." "$LINENO"
         kill "$pid"
+        cleanup_pid
         log_message "INFO" "$APP_NAME service stopped." "$LINENO"
     else
         log_message "WARN" "No active $APP_NAME process found for PID $pid. Cleaning up stale PID file." "$LINENO"
         cleanup_pid
     fi
+}
+
+# Function: Restart the service
+restart_service() {
+    if [[ ! -f "$PID_FILE" ]]; then
+        log_message "INFO" "No $APP_NAME service is currently running." "$LINENO"
+        exit 0
+    fi
+
+    log_message "INFO" "Restarting $APP_NAME service with PID $pid..." "$LINENO"
+    stop_service
+    start_service
 }
 
 # Function: Check the status of the service
@@ -626,21 +639,25 @@ start_process() {
     fi
 
     # Check if an instance is already running
-    check_already_running
-
-    # Log and start the configuration
-    log_message "INFO" "Starting $APP_NAME: $(date)" "$LINENO"
-    show_config
-
-    # Start the service or run interactively
-    if [[ "$START_SERVICE" == true ]]; then
-        start_service
+    if [[ "$RESTART_SERVICE" == true ]]; then
+        restart_service
     else
-        log_message "INFO" "Running network check interactively..." "$LINENO"
-        # Set up a trap for cleanup on termination
-        trap 'cleanup_pid' EXIT
-        echo $$ >"$PID_FILE"
-        main
+        check_already_running
+
+        # Log and start the configuration
+        log_message "INFO" "Starting $APP_NAME: $(date)" "$LINENO"
+        show_config
+
+        # Start the service or run interactively
+        if [[ "$START_SERVICE" == true ]]; then
+            start_service
+        else
+            log_message "INFO" "Running $APP_NAME interactively..." "$LINENO"
+            # Set up a trap for cleanup on termination
+            trap 'cleanup_pid' EXIT
+            echo $$ >"$PID_FILE"
+            main
+        fi
     fi
 }
 
@@ -775,15 +792,15 @@ show_help() {
     # Configuration and Initialization
     printf "\nConfiguration and Initialization:\n"
     printf "  -c, --config <config_file>  Specify a custom configuration file (default: %s).\n" "${CONFIG_FILE}"
-    printf "  -I, --init                  Initialize the configuration file.\n"
-    printf "  -F, --force-init            Force initialize of the configuration file if one exists.\n"
-    printf "  -s, --show-config           Show the configuration settings.\n"
-    printf "  -S, --show-config-file      Show the configuration file.\n"
+    printf "  -i, --init                  Initialize the configuration file.\n"
+    printf "  -f, --force-init            Force initialize of the configuration file if one exists.\n"
+    printf "  -S, --show-config           Show the configuration settings.\n"
+    printf "  -e, --show-config-file      Show the configuration file.\n"
 
     # Cache Management
     printf "\nCache Management:\n"
-    printf "  -C, --clean                 Delete all cached files.\n"
-    printf "  -k, --cache-dir  <path>     Specify a custom cache directory (default: %s).\n" "$CACHE_DIR}"
+    printf "  -x, --clean                 Delete all cached files.\n"
+    printf "  -C, --cache-dir  <path>     Specify a custom cache directory (default: %s).\n" "$CACHE_DIR}"
 
     # Notification Options
     printf "\nNotification Options:\n"
@@ -800,18 +817,19 @@ show_help() {
     printf "  -o, --output <file>       Specify a custom log file location (default: %s).\n" "${LOG_FILE}"
     printf "  -L, --log-level <level>   Set the log level (FATAL, ERROR, WARN, INFO, DEBUG).\n"
 
-    # Network Check Configuration
-    printf "\nNetwork Check Configuration:\n"
-    printf "  -i, --interval <seconds>    Set the interval between checks (default: %d seconds).\n" "${CHECK_INTERVAL}"
+    # Remote Connection Configuration
+    printf "\nRemote Connection Configuration:\n"
+    printf "  -I, --interval <seconds>    Set the interval between checks (default: %d seconds).\n" "${CHECK_INTERVAL}"
     printf "  -T, --timeout <seconds>     Set the connection timeout for remote connections (default: %d seconds).\n" "${TIMEOUT}"
     printf "  -P, --ping-target <IP>      Set a custom ping target (default: %s).\n" "${PING_TARGET}"
     printf "  -D, --dns-test-domain <domain>  Set a custom DNS test domain (default: %s).\n" "${DNS_TEST_DOMAIN}"
 
     # Process Management Functions
     printf "\nProcess Management:\n"
-    printf "  -r, --start                 Start the network check service in the background.\n"
-    printf "  -t, --stop                  Stop the network check service.\n"
-    printf "  -z, --status                Check the current status of the network check service.\n"
+    printf "  -s, --start                 Start the %s service in the background.\n" "${APP_NAME}"
+    printf "  -k, --stop                  Stop the %s service.\n" "${APP_NAME}"
+    printf "  -r, --restart               Restart the %s service.\n" "${APP_NAME}"
+    printf "  -t, --status                Check the current status of the %s service.\n" "${APP_NAME}"
 
     # Examples
     printf "\nExamples:\n"
@@ -869,24 +887,24 @@ parse_arguments() {
             CLI_CONFIG_FILE=true
             shift
             ;;
-        --init | -I)
+        --init | -i)
             INIT=true
             ;;
-        --force-init | -F)
+        --force-init | -f)
             INIT_FORCE=true
             ;;
-        --show-config | -s)
+        --show-config | -S)
             SHOW_CONFIG=true
             ;;
-        --show-config-file | -S)
+        --show-config-file | -e)
             SHOW_CONFIG_FILE=true
             ;;
 
         # Cache Management
-        --clean | -C)
+        --clean | -x)
             CLEAN=true
             ;;
-        --cache-dir | -k)
+        --cache-dir | -C)
             if [[ -z "$2" || "$2" == -* ]]; then
                 printf "Error: %s requires a value\n" "$1" >&2
                 exit 1
@@ -957,8 +975,8 @@ parse_arguments() {
             fi
             ;;
 
-        # Network Check Configuration
-        --interval | -i)
+        # Remote Connection Configuration
+        --interval | -I)
             if [[ -z "$2" || "$2" == -* ]]; then
                 printf "Error: %s requires a value\n" "$1" >&2
                 exit 1
@@ -997,13 +1015,16 @@ parse_arguments() {
             ;;
 
         # Process Management
-        --start | -r)
+        --start | -s)
             START_SERVICE=true
             ;;
-        --stop | -t)
+        --stop | -k)
             STOP_SERVICE=true
             ;;
-        --status | -z)
+        --restart | -r)
+            RESTART_SERVICE=true
+            ;;
+        --status | -t)
             SHOW_STATUS=true
             ;;
 
